language: cpp

# matrix:
#   include:
#     # works on Precise and Trusty
#     - os: linux
#       sudo: required
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#       compiler:
#         - gcc
# 	- clang

# before_install:
#     - eval "${MATRIX_EVAL}"


os: linux
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    - libgsl0-dev # on trusty
    - libboost-python-dev # for easykf

#env:
#  - CC=gcc-7 CXX=g++-7  # For some reasons this is overwritten
compiler:
  - gcc
  - clang


install:
  - export CC=gcc-7 CXX=g++-7
  - export NB_JOBS=2
  - echo "Installing dependencies"
  - git clone https://github.com/cjlin1/libsvm.git # Dependency for libsvm
  - cd libsvm && make lib
  - sudo mkdir /usr/include/libsvm && sudo cp svm.h /usr/include/libsvm/
  - sudo cp libsvm.so.2 /usr/lib/ && sudo ln -s /usr/lib/libsvm.so.2 /usr/lib/libsvm.so
  - cd ..
  - git clone https://github.com/HerveFrezza-Buet/vq2.git # Dependency for gaml-kvq
  - cd vq2 && mkdir -p build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && sudo make install -j$NB_JOBS && cd ../..
  - git clone https://github.com/jeremyfix/easykf.git # Dependencies for gaml-mlp
  - cd easykf && mkdir -p build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/usr && sudo make install -j$NB_JOBS && cd ../..
  - >
    echo "Building gaml"                  
    && cd gaml                              
    && mkdir -p build                       
    && cd build                             
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    && sudo make install -j$NB_JOBS
    && cd ../..
  - >
    echo "Building gaml-linear"
    && cd gaml-linear                      
    && mkdir -p build                      
    && cd build                           
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    && sudo make install -j$NB_JOBS              
    && cd ../..
  - >
    echo "Building gaml-xtree"
    && cd gaml-xtree                    
    && mkdir -p build                    
    && cd build				
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    && sudo make install -j$NB_JOBS
    && cd ../..
  - >
    echo "Building gaml-kvq"
    && cd gaml-kvq
    && mkdir -p build
    && cd build  
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    && sudo make install -j$NB_JOBS   
    && cd ../..
  - >
    echo "Building gaml-mlp"
    && cd gaml-mlp
    && mkdir -p build
    && cd build               
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    && sudo make install -j$NB_JOBS       
    && cd ../..
  - >
    echo "Building gaml-libsvm"
    && cd gaml-libsvm 
    && mkdir -p build
    && cd build
    && cmake .. -DCMAKE_INSTALL_PREFIX=/usr
    && sudo make install -j$NB_JOBS  
    && cd ../..
  - echo "Installation finished"

script:
  - echo "Running all the examples"
  - >
    echo "Testing gaml"
    cd gaml/travis
    && sh test.sh
    && cd ../..
  - >
    echo "Testing gaml-libsvm"
    cd gaml-libsvm/travis
    && sh test.sh
    && cd ../..  
  - >
    echo "Testing gaml-linear"
    cd gaml-linear/travis
    && sh test.sh
    && cd ../..  
  - >
    echo "Testing gaml-xtree"
    cd gaml-xtree/travis
    && sh test.sh
    && cd ../..  
  - >
    echo "Testing gaml-mlp"
    cd gaml-mlp/travis
    && sh test.sh
    && cd ../..  
  - echo "Done"