os: linux
language: minimal

services:
    - docker

before_install:
    - docker build -t gaml/latest .
    - docker run gaml /bin/sh -c "cd gaml/gaml/travis; ./test.sh"
    - docker run gaml /bin/sh -c "cd gaml/gaml-linear/travis; ./test.sh"
    - docker run gaml /bin/sh -c "cd gaml/gaml-libsvm/travis; ./test.sh"
    - docker run gaml /bin/sh -c "cd gaml/gaml-datasets/travis; ./test.sh"
    - docker run gaml /bin/sh -c "cd gaml/gaml-xtree/travis; ./test.sh"
    - docker run gaml /bin/sh -c "cd gaml/gaml-mlp/travis; ./test.sh"
