language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

sudo: required

addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

install:

script:
  - cd gaml
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ../..
  - cd gaml-linear
  - mkdir build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ../..