language: cpp

# matrix:
#   include:
#     # works on Precise and Trusty
#     - os: linux
#       sudo: required
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#       compiler:
#         - gcc
# 	- clang

# before_install:
#     - eval "${MATRIX_EVAL}"


os: linux
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    - libgsl0-dev # on trusty

#env:
#  - CC=gcc-7 CXX=g++-7  # For some reasons this is overwritten
compiler:
  - gcc
  - clang


install:
  - export CC=gcc-7 CXX=g++-7

script:
  - echo "Building gaml"
  - cd gaml
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install -j2
  - cd ../..
  - echo "Building gaml-linear"
  - cd gaml-linear
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install -j2
  - cd ../..
