language: cpp

# matrix:
#   include:
#     # works on Precise and Trusty
#     - os: linux
#       sudo: required
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#       compiler:
#         - gcc
# 	- clang

# before_install:
#     - eval "${MATRIX_EVAL}"


os: linux
sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7

env:
  - CC=gcc-7 CXX=g++-7
compiler:
  - gcc
  - clang



install:

script:
  - echo "Building gaml"
  - cd gaml
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ../..
  - echo "Building gaml-linear"
  - cd gaml-linear
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ../..
